/**
 * ESLint flat config — Qalaam root.
 * Per CLAUDE.md §11.2: TypeScript strict + import ordering + no-unused enforcement.
 *
 * Per-package overrides live in `packages/<name>/eslint.config.js` extending this base.
 */
import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import importPlugin from 'eslint-plugin-import';
import unicorn from 'eslint-plugin-unicorn';
import unusedImports from 'eslint-plugin-unused-imports';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/coverage/**',
      'packages/types-ts/dist/**', // generated
      '**/*.config.js',
      '**/*.config.ts',
      '**/*.config.mjs',
      '**/*.config.cjs',
      // lint-staged config — function form needs CJS module-system, not in
      // a TS project, eslint-typescript can't parse it via project service.
      '.lintstagedrc.cjs',
      '**/.lintstagedrc.cjs',
      // One-shot ingest scripts run via tsx; not part of any tsconfig project.
      'scripts/data/ingest-qul-*.ts',
      // QA scripts (smoke-sweep.mjs etc.) are standalone Node ESM scripts
      // outside the workspace tsconfig graph.
      'scripts/qa/**',
      // Test files in packages whose tsconfig excludes the tests/ dir —
      // covered by vitest's own typecheck per the existing convention.
      // `**/` prefix so absolute-path invocations (lint-staged) match.
      '**/packages/data-loader/tests/qul-readers.test.ts',
      '**/apps/backend/tests/qul-routes.test.ts',
      '**/packages/api-client-ts/tests/qf-tier-b.test.ts',
      '**/packages/tajweed-detector/tests/tajweed-detector.test.ts',
      // Generated by Next.js on every build.
      '**/apps/web/next-env.d.ts',
      // Mobile (Expo) doesn't share the workspace tsconfig project graph;
      // typecheck via apps/mobile/tsconfig.json + Expo tooling instead.
      'apps/mobile/**',
      '**/apps/mobile/**',
      // Scrape-ingest runs via tsx; not in any tsconfig project.
      'scripts/data/ingest-qul-from-scrape.ts',
      // Codegen runner is invoked via tsx from the @qalaam/schema
      // codegen script; outside the workspace tsconfig project graph.
      'tooling/codegen/run.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      import: importPlugin,
      'unused-imports': unusedImports,
      unicorn,
    },
    rules: {
      // Type safety
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/consistent-type-exports': 'error',
      '@typescript-eslint/no-import-type-side-effects': 'error',

      // Imports
      'import/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'type'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'import/no-default-export': 'warn',
      'import/no-cycle': 'error',
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'warn',
        { vars: 'all', varsIgnorePattern: '^_', args: 'after-used', argsIgnorePattern: '^_' },
      ],

      // Quality
      'unicorn/filename-case': ['error', { cases: { kebabCase: true, pascalCase: true } }],
      'unicorn/no-array-for-each': 'off', // we prefer for...of but forEach is fine
      'unicorn/prefer-node-protocol': 'error',
      'unicorn/no-null': 'off', // null is meaningful in our schema
      'no-console': ['error', { allow: ['warn', 'error'] }], // pino in production per CLAUDE.md
      eqeqeq: ['error', 'always'],
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },

  // Test files: relax some strictness
  {
    files: ['**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', '**/tests/**'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      'no-console': 'off',
    },
  },

  // Config files: allow default exports
  {
    files: ['**/*.config.{ts,mts,cts}', '**/vite.config.ts', '**/vitest.config.ts'],
    rules: {
      'import/no-default-export': 'off',
    },
  },

  // Fastify plugins + route handlers: the plugin signature is
  // `(fastify, opts) => Promise<void>`, even when the body is synchronous
  // (every route registration is `fastify.get(...)` which returns sync).
  // Same for `app.setErrorHandler(async ...)` — the handler must be async
  // even if it only returns a reply. Sprinkling
  // `eslint-disable-next-line @typescript-eslint/require-await` across
  // every route file is noise; scoping the rule off where Fastify
  // mandates the shape is cleaner.
  {
    files: [
      '**/apps/backend/src/server.ts',
      '**/apps/backend/src/plugins/**/*.ts',
      '**/apps/backend/src/routes/**/*.ts',
      '**/apps/backend/src/lib/mcp-quran-ai.ts',
    ],
    rules: {
      '@typescript-eslint/require-await': 'off',
    },
  },

  // Apply prettier last to disable rules that conflict with formatting
  prettier,
);
