#!/usr/bin/env bash
# Emit the 604 @font-face declarations for the QPC V4 Tajweed page fonts.
#
# Output: apps/web/src/styles/qpc-v4-fonts.css — imported from globals.css.
# Each page gets its own font family `QPCv4Page<N>` because the per-page
# COLR fonts share the same PUA codepoint range (U+FC41-FC64) but draw
# DIFFERENT glyphs per page — using one family for all 604 pages would
# render the wrong glyph.
#
# `unicode-range: U+FC41-U+FC64` is set on every @font-face so the
# browser only fetches the page font when one of those PUA codepoints
# appears. font-display: block so the verse never renders in fallback.

set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
# Emit to public/ — this CSS is loaded LAZILY (only when the user picks
# the tajweed layout) by lib/load-tajweed-css.ts. Putting it in src/styles
# would have Next.js inline it into the global stylesheet that ships on
# every route, parsing 540KB of @font-palette-values rules even for
# users who never enable tajweed mode. That parse cost was the cause of
# the sluggishness + STATUS_BREAKPOINT crashes.
OUT_CSS="${REPO_ROOT}/apps/web/public/qpc-v4-fonts.css"

cat > "${OUT_CSS}" <<'HEADER'
/*
 * QPC V4 Tajweed page fonts — auto-generated by
 * scripts/data/generate-qpc-v4-fontface-css.sh. DO NOT edit by hand;
 * re-run the script if you re-download the fonts.
 *
 * Each of the 604 mushaf pages has its own COLR/CPAL color font
 * carrying that page's glyphs at PUA codepoints U+FC41-U+FC64. The
 * frontend AyahCard reads `text_qpc_v4` + `page_qpc_v4` from
 * /v1/qpc-text/:vk, sets fontFamily to `QPCv4Page<N>`, and renders
 * the canonical KFGQPC V4 1441H tajweed mushaf — colors come from
 * the font's CPAL palette, which we override below for a Qalaam-
 * specific look.
 *
 * Sourced from Quran Foundation:
 *   https://verses.quran.foundation/fonts/quran/hafs/v4/colrv1/woff2/p{N}.woff2
 *
 * License: KFGQPC reuse terms (kfgqpc-terms LicenseTag).
 * Per-font SHA256 pinned in data/qul-source/qpc-v4-fonts.sha256 (ADR-0002).
 *
 * ─────────────────────────────────────────────────────────────────
 * Qalaam tajweed palette — overrides KFGQPC default CPAL palette 0
 * via @font-palette-values. The default ships with saturated primary
 * colors (bright red, royal blue, kelly green) — that's the
 * Quran.com / verses.quran.foundation look. Distinctive but
 * commodified.
 *
 * Qalaam's signature: warm-earth Persian-illumination palette —
 * terracotta for qalqalah, sage for ghunnah, bronze for sukun, sand
 * for silent letters. Reads as a single coherent ink wash with
 * accent colors only where the rule actually changes pronunciation.
 *
 * CPAL slot reference (extracted from QPCv4Page1.woff2 palette 0):
 *   [0]  base ink              [1,2,15] silent letters / hamzat wasl
 *   [3]  qalqalah              [4]      madd 4-5
 *   [5]  madd 2                [6]      ghunnah / nun mushaddadah
 *   [7]  idghaam-no-ghunnah    [8]      idghaam-shafawi (alt blue)
 *   [9]  madd 6 (lazim)        [10]     laam (idghaam-mutaqaribayn)
 *   [11] sukun emphasis        [12]     ikhfa background tint
 *   [13,14] base ink dup
 *
 * `--qalaam-tajweed`           — refined warm-earth palette.
 * `--qalaam-tajweed-highlight` — every slot collapsed to brand gold,
 *                                used inside .recite-highlight so the
 *                                active word reads as ONE highlighted
 *                                unit even when it crosses several
 *                                CPAL slots.
 */
HEADER

# Qalaam refined-earth palette (overrides CPAL palette 0). v2: pushed
# the saturation/contrast up after the v1 palette read as too washed
# against the warm-paper background. Still firmly NOT the Quran.com
# primary-color look — terracotta-and-sage instead of red-and-blue —
# but with enough punch that the rules read at a glance.
#   [0] base ink      [1,2,15] silent / hamzat-wasl (warm sand)
#   [3] qalqalah      [4] madd 4-5      [5] madd 2
#   [6] ghunnah       [7] idghaam-no-ghunnah  [8] idghaam-shafawi
#   [9] madd 6 lazim  [10] laam idghaam [11] sukun
#   [12] ikhfa bg
TAJWEED_PALETTE_LIGHT='    0 #1f1410,    1 #9a8166,    2 #9a8166,    3 #b03a1a,    4 #d49011,    5 #e0b14d,    6 #2f8a5a,    7 #2c5a82,    8 #4d8aa8,    9 #c45323,   10 #5a9b6e,   11 #b78a30,   12 #f0dcb4,   13 #1f1410,   14 #1f1410,   15 #9a8166'

# Highlight palette — every slot painted brand gold so the active word
# reads as a single highlighted unit even when the glyph spans several
# CPAL color indices. v2: bumped to leaf-700 (#8a6614) on stroke slots
# for stronger contrast against the sand-pill background, kept the
# light-gold spread on edge accents.
TAJWEED_PALETTE_HIGHLIGHT='    0 #8a6614,    1 #c69426,    2 #c69426,    3 #8a6614,    4 #8a6614,    5 #8a6614,    6 #8a6614,    7 #8a6614,    8 #c69426,    9 #8a6614,   10 #8a6614,   11 #8a6614,   12 #fdf2cc,   13 #8a6614,   14 #8a6614,   15 #c69426'

for n in $(seq 1 604); do
  # One line per declaration — keeps the file scannable in a diff and
  # cuts byte count roughly in half vs the multi-line form (a 50%
  # reduction matters when this CSS is 540KB+ and used to live in the
  # global stylesheet that ships on every route).
  echo "@font-face{font-family:'QPCv4Page${n}';src:url('/fonts/quran-tajweed-v4/p${n}.woff2') format('woff2');font-display:block;font-weight:400;unicode-range:U+FC41-U+FC64}" >> "${OUT_CSS}"
  echo "@font-palette-values --qalaam-tajweed{font-family:'QPCv4Page${n}';base-palette:0;override-colors:${TAJWEED_PALETTE_LIGHT}}" >> "${OUT_CSS}"
  echo "@font-palette-values --qalaam-tajweed-highlight{font-family:'QPCv4Page${n}';base-palette:0;override-colors:${TAJWEED_PALETTE_HIGHLIGHT}}" >> "${OUT_CSS}"
done

lines=$(wc -l < "${OUT_CSS}")
echo "[generate-qpc-v4-fontface-css] wrote ${OUT_CSS} (${lines} lines, 604 @font-face)"
