#!/usr/bin/env bash
# Emit the 604 @font-face declarations for the QPC V4 Tajweed page fonts.
#
# Output: apps/web/src/styles/qpc-v4-fonts.css — imported from globals.css.
# Each page gets its own font family `QPCv4Page<N>` because the per-page
# COLR fonts share the same PUA codepoint range (U+FC41-FC64) but draw
# DIFFERENT glyphs per page — using one family for all 604 pages would
# render the wrong glyph.
#
# `unicode-range: U+FC41-U+FC64` is set on every @font-face so the
# browser only fetches the page font when one of those PUA codepoints
# appears. font-display: block so the verse never renders in fallback.

set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUT_CSS="${REPO_ROOT}/apps/web/src/styles/qpc-v4-fonts.css"

cat > "${OUT_CSS}" <<'HEADER'
/*
 * QPC V4 Tajweed page fonts — auto-generated by
 * scripts/data/generate-qpc-v4-fontface-css.sh. DO NOT edit by hand;
 * re-run the script if you re-download the fonts.
 *
 * Each of the 604 mushaf pages has its own COLR/CPAL color font
 * carrying that page's glyphs at PUA codepoints U+FC41-U+FC64. The
 * frontend AyahCard reads `text_qpc_v4` + `page_qpc_v4` from
 * /v1/qpc-text/:vk, sets fontFamily to `QPCv4Page<N>`, and renders
 * the canonical KFGQPC V4 1441H tajweed mushaf — colors baked into
 * the font, no CSS overlay.
 *
 * Sourced from Quran Foundation:
 *   https://verses.quran.foundation/fonts/quran/hafs/v4/colrv1/woff2/p{N}.woff2
 *
 * License: KFGQPC reuse terms (kfgqpc-terms LicenseTag).
 * Per-font SHA256 pinned in data/qul-source/qpc-v4-fonts.sha256 (ADR-0002).
 */
HEADER

for n in $(seq 1 604); do
  cat >> "${OUT_CSS}" <<EOF
@font-face {
  font-family: 'QPCv4Page${n}';
  src: url('/fonts/quran-tajweed-v4/p${n}.woff2') format('woff2');
  font-display: block;
  font-weight: 400;
  unicode-range: U+FC41-U+FC64;
}
EOF
done

lines=$(wc -l < "${OUT_CSS}")
echo "[generate-qpc-v4-fontface-css] wrote ${OUT_CSS} (${lines} lines, 604 @font-face)"
