#!/usr/bin/env python3
# ruff: noqa: E501, S324, PLR2004, PLW2901
"""scrape-qul-full.py — exhaustive QUL resource scraper.

Walks every resource catalogued in `/tmp/qul-inventory.json` (or a fresh
scrape if missing), logs into qul.tarteel.ai, follows each detail page,
captures the Active-Storage signed download URL on each Download button,
downloads the file, unpacks zip envelopes, and stages bytes under
`data/qul-source/raw/<category>/<id>-<slugged-title>.<ext>` with a
sidecar `<file>.license.json` carrying source URL + sha256 +
license_tag placeholder.

Per ADR-0020 + ADR-0002:
  * Every file gets a sha256 pin in its sidecar license.json.
  * license_tag defaults to `unverified` — the existing ingest
    framework refuses unverified files. The user must edit each
    sidecar to confirm the licence (or batch-confirm via tag-by-source).
  * Files stage under data/qul-source/raw/ for the existing
    ingest-qul-*.ts/.py scripts to consume; nothing is committed
    to .git (.gitignored).

Credentials: env QUL_EMAIL / QUL_PASSWORD. Read from
~/.claude/projects/-home-onnyx-qalam/memory/reference_qul_credentials.md
if you ever need them.

Usage:
    QUL_EMAIL=...@gmail.com QUL_PASSWORD=... python3 scripts/data/scrape-qul-full.py
    # or filter to a subset:
    --categories quran-script,mushaf-layout,font
    --limit 50
    --resume   (default: skip already-downloaded files)
    --no-resume

Concurrency: 4 simultaneous downloads (polite to the QUL server).
Idempotent: re-running with --resume picks up where it stopped.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import hashlib
import html
import json
import logging
import os
import re
import sys
import time
import zipfile
from pathlib import Path

try:
    import requests
except ImportError:
    print("FATAL: pip install requests beautifulsoup4", file=sys.stderr)
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
RAW_DIR = REPO_ROOT / "data" / "qul-source" / "raw"
# Inventory JSON is regenerated by /tmp/qul-parse.py before running this
# script; staging in /tmp is intentional (large file, no PII, regenerable).
INVENTORY_JSON = Path("/tmp/qul-inventory.json")  # noqa: S108

QUL_BASE = "https://qul.tarteel.ai"
USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/121.0 Safari/537.36"
)

# All 14 QUL resource categories
ALL_CATEGORIES = (
    "ayah-theme",
    "ayah-topics",
    "font",
    "morphology",
    "mushaf-layout",
    "mutashabihat",
    "quran-metadata",
    "quran-script",
    "recitation",
    "similar-ayah",
    "surah-info",
    "tafsir",
    "translation",
    "transliteration",
)

logging.basicConfig(
    format="%(asctime)s %(levelname)-7s %(message)s",
    datefmt="%H:%M:%S",
    level=logging.INFO,
)
log = logging.getLogger("qul-scrape")


def slugify(s: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_\-]+", "-", s.lower()).strip("-")
    return s[:60] or "resource"


def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(64 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def login(session: requests.Session, email: str, password: str) -> None:
    """POST to /users/sign_in. Sets remember_user_token cookie on success."""
    log.info("signing in as %s", email)
    r = session.get(f"{QUL_BASE}/users/sign_in")
    r.raise_for_status()
    token_match = re.search(r'name="authenticity_token" value="([^"]+)"', r.text)
    if not token_match:
        raise RuntimeError("no CSRF token on sign-in form")
    token = token_match.group(1)

    r = session.post(
        f"{QUL_BASE}/users/sign_in",
        data={
            "authenticity_token": token,
            "user[email]": email,
            "user[password]": password,
            "user[remember_me]": "1",
            "commit": "Sign in",
        },
        allow_redirects=True,
    )
    r.raise_for_status()
    if "remember_user_token" not in session.cookies.get_dict():
        raise RuntimeError("login failed (no remember_user_token cookie)")
    log.info("login OK")


def fetch_inventory() -> dict[str, list[dict]]:
    """Read parsed inventory JSON, or rebuild it if missing."""
    if INVENTORY_JSON.exists():
        return json.loads(INVENTORY_JSON.read_text())
    log.warning("inventory JSON missing at %s — please run /tmp/qul-parse.py first", INVENTORY_JSON)
    sys.exit(2)


def find_download_urls(detail_html: str, *, category: str) -> list[tuple[str, str, str]]:
    """Extract (url, format, filename) from a resource detail page.

    QUL renders download links in three patterns:
      1. Direct CDN: `https://static-cdn.tarteel.ai/...` (some recitations, fonts).
      2. Active-Storage redirect: `/rails/active_storage/blobs/redirect/<token>/<filename>`.
      3. **Per-resource hashed download route**: `/resources/<category>/<hash>/download`
         — most metadata, morphology, surah-info, transliteration, mutashabihat,
         similar-ayah, and ayah-theme expose downloads via this route. The route
         302-redirects to the actual file.

    For pattern 3 we capture the route URL and let the requests session follow
    redirects on download. The extension is unknown until we hit the redirect,
    so we infer from the page's "Download <format>" button text.
    """
    out: list[tuple[str, str, str]] = []
    ext_pattern = re.compile(
        r'\.(zip|sqlite|json|ttf|woff2?|otf|csv|db|tar|tar\.gz|gz)(?:\?|$|"|\s)', re.I
    )

    # Pattern 1: Direct CDN URLs anywhere on the page
    for m in re.finditer(
        r'https://static-cdn\.tarteel\.ai/[^"\'<>\s]+\.(?:zip|sqlite|json|ttf|woff2?|otf|csv|db|tar|tar\.gz|gz)',
        detail_html,
    ):
        url = m.group(0)
        ext_match = ext_pattern.search(url)
        ext = ext_match.group(1).lower() if ext_match else "bin"
        fname = url.rsplit("/", 1)[-1].split("?", 1)[0]
        out.append((url, ext, fname))

    # Pattern 2: Active-Storage redirect URLs
    for m in re.finditer(
        r'href="(/rails/active_storage/[^"]+)"',
        detail_html,
    ):
        url = m.group(1)
        if url.startswith("/"):
            url = QUL_BASE + url
        fname_match = re.search(r"/([^/]+\.\w+)$", url)
        fname = fname_match.group(1) if fname_match else "download.bin"
        ext_match = ext_pattern.search(fname)
        ext = ext_match.group(1).lower() if ext_match else "bin"
        out.append((url, ext, fname))

    # Pattern 3: per-resource hashed /download route. Multiple format buttons
    # (sqlite / json / db / etc.) emit the same /<hash>/download path with
    # query-param fmt= or distinct hash per format — let's capture every
    # occurrence and pair with its button text (which carries the format hint).
    for m in re.finditer(
        rf'href="(/resources/{re.escape(category)}/[a-f0-9]{{20,}}/download(?:\?[^"]*)?)"[^>]*>([^<]*)',
        detail_html,
    ):
        url = QUL_BASE + m.group(1)
        button_text = m.group(2).strip().lower()
        # Format hint from button text or fmt= query param
        ext = "bin"
        for k in ("sqlite", "json", "csv", "db", "zip", "tar", "gz", "ttf", "woff2", "woff", "otf"):
            if k in button_text or f"fmt={k}" in url:
                ext = k
                break
        # Make filename predictable
        fname = f"download-via-302.{ext}"
        out.append((url, ext, fname))

    # Dedupe — preserve order
    seen = set()
    deduped = []
    for u, e, f in out:
        if u in seen:
            continue
        seen.add(u)
        deduped.append((u, e, f))
    return deduped


def license_metadata_from_detail(detail_html: str) -> dict[str, str]:
    """Pull license-relevant text from the detail page (when QUL surfaces it)."""
    meta: dict[str, str] = {}
    # license tag chips
    for m in re.finditer(
        r"<span>([A-Za-z][A-Za-z\s+\-]+(?:License|MIT|GPL|Apache|CC[\s\-]BY|Public Domain|KFGQPC|Copyright)[^<]*)</span>",
        detail_html,
    ):
        meta.setdefault("license_chip", html.unescape(m.group(1).strip()))

    # tags in chip rows
    tags = re.findall(
        r'data-turbo-frame="resources"[^>]*>\s*<span>([^<]+)</span>',
        detail_html,
    )
    if tags:
        meta["tags"] = ", ".join(html.unescape(t) for t in tags[:8])
    return meta


def write_sidecar(
    path: Path,
    *,
    source_url: str,
    source_id: int,
    category: str,
    title: str,
    license_meta: dict[str, str],
) -> None:
    """Sidecar JSON next to each downloaded file — ADR-0020 license envelope."""
    sidecar = path.with_suffix(path.suffix + ".license.json")
    sha = sha256_file(path)
    payload = {
        "source": "QUL (Quranic Universal Library)",
        "source_url": source_url,
        "source_id": source_id,
        "category": category,
        "title": title,
        "sha256": sha,
        "downloaded_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "license_tag": "unverified",  # user MUST edit before ingest
        "license_chip": license_meta.get("license_chip", ""),
        "tags": license_meta.get("tags", ""),
        "attribution_required": True,  # default-on per ADR-0020
        "notes": "",
    }
    sidecar.write_text(json.dumps(payload, indent=2, ensure_ascii=False))


def download_one(
    session: requests.Session, *, category: str, resource: dict, out_dir: Path, resume: bool
) -> tuple[bool, str]:
    """Walk one resource detail page → download every linked file."""
    rid = resource["id"]
    title = resource["title"]
    detail_url = f"{QUL_BASE}/resources/{category}/{rid}"
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        r = session.get(detail_url, timeout=30)
    except Exception as e:
        return False, f"detail-fetch failed: {e}"
    if r.status_code != 200:
        return False, f"detail HTTP {r.status_code}"

    urls = find_download_urls(r.text, category=category)
    license_meta = license_metadata_from_detail(r.text)

    if not urls:
        return False, "no download URLs found"

    success_count = 0
    seen_paths: set[Path] = set()
    for url, ext, _fname in urls:
        slug = slugify(title)
        # Canonical filename. For each format, append a 4-char hash of
        # the URL so multiple formats from the same resource don't clobber.
        url_tag = hashlib.md5(url.encode()).hexdigest()[:6]
        out_name = f"{rid}-{slug}-{url_tag}.{ext}"
        out_path = out_dir / out_name

        if resume and out_path.exists() and out_path.stat().st_size > 0:
            success_count += 1
            seen_paths.add(out_path)
            continue

        try:
            with session.get(url, stream=True, timeout=180, allow_redirects=True) as resp:
                resp.raise_for_status()
                # If we used a /<hash>/download route, the redirect's
                # Content-Disposition reveals the real filename + ext.
                cd = resp.headers.get("content-disposition", "")
                cd_match = re.search(r'filename="?([^";]+)"?', cd)
                if cd_match and ext == "bin":
                    real_name = cd_match.group(1)
                    real_ext_m = re.search(
                        r"\.(zip|sqlite|json|ttf|woff2?|otf|csv|db|tar|gz)$", real_name, re.I
                    )
                    if real_ext_m:
                        ext = real_ext_m.group(1).lower()
                        out_name = f"{rid}-{slug}-{url_tag}.{ext}"
                        out_path = out_dir / out_name
                tmp = out_path.with_suffix(out_path.suffix + ".partial")
                with tmp.open("wb") as f:
                    for chunk in resp.iter_content(chunk_size=64 * 1024):
                        f.write(chunk)
                tmp.replace(out_path)
        except Exception as e:
            return False, f"download {url}: {e}"

        write_sidecar(
            out_path,
            source_url=url,
            source_id=rid,
            category=category,
            title=title,
            license_meta=license_meta,
        )

        if ext == "zip":
            try:
                with zipfile.ZipFile(out_path) as zf:
                    zf.extractall(out_dir / f"{rid}-{slug}")
            except zipfile.BadZipFile:
                pass

        seen_paths.add(out_path)
        success_count += 1

    return True, f"{success_count}/{len(urls)} files"


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--categories",
        default=",".join(ALL_CATEGORIES),
        help="comma-separated category list (default: all 14)",
    )
    parser.add_argument(
        "--limit", type=int, default=0, help="max resources per category (0 = no limit)"
    )
    parser.add_argument(
        "--no-resume", action="store_true", help="re-download even if file already exists"
    )
    parser.add_argument(
        "--concurrency", type=int, default=4, help="simultaneous downloads (default: 4 — be polite)"
    )
    parser.add_argument("--dry-run", action="store_true", help="print plan, don't download")
    args = parser.parse_args()

    email = os.environ.get("QUL_EMAIL", "").strip()
    password = os.environ.get("QUL_PASSWORD", "").strip()
    if not email or not password:
        print("ERR: set QUL_EMAIL and QUL_PASSWORD env vars.", file=sys.stderr)
        sys.exit(2)

    inventory = fetch_inventory()
    cats = [c.strip() for c in args.categories.split(",") if c.strip()]
    invalid = set(cats) - set(ALL_CATEGORIES)
    if invalid:
        print(f"ERR: unknown categories {invalid}. Valid: {ALL_CATEGORIES}", file=sys.stderr)
        sys.exit(2)

    plan: list[tuple[str, dict]] = []
    for cat in cats:
        rows = inventory.get(cat, [])
        if args.limit:
            rows = rows[: args.limit]
        plan.extend((cat, r) for r in rows)

    log.info("plan: %d resources across %d categories", len(plan), len(cats))
    if args.dry_run:
        for cat, r in plan[:30]:
            log.info("  %s/%s  %s", cat, r["id"], r["title"][:60])
        if len(plan) > 30:
            log.info("  … (%d more)", len(plan) - 30)
        return

    session = requests.Session()
    session.headers["User-Agent"] = USER_AGENT
    session.cookies.clear()
    login(session, email, password)

    counters = {"ok": 0, "fail": 0, "skip": 0}

    def worker(cat: str, resource: dict) -> tuple[str, dict, bool, str]:
        out_dir = RAW_DIR / cat
        success, message = download_one(
            session,
            category=cat,
            resource=resource,
            out_dir=out_dir,
            resume=not args.no_resume,
        )
        return cat, resource, success, message

    with concurrent.futures.ThreadPoolExecutor(max_workers=args.concurrency) as ex:
        futs = [ex.submit(worker, c, r) for c, r in plan]
        for i, fut in enumerate(concurrent.futures.as_completed(futs), 1):
            cat, resource, success, message = fut.result()
            if success:
                counters["ok"] += 1
                log.info(
                    "[%4d/%d] OK   %s/%-4s  %s  (%s)",
                    i,
                    len(plan),
                    cat,
                    resource["id"],
                    resource["title"][:50],
                    message,
                )
            else:
                counters["fail"] += 1
                log.warning(
                    "[%4d/%d] FAIL %s/%-4s  %s  → %s",
                    i,
                    len(plan),
                    cat,
                    resource["id"],
                    resource["title"][:50],
                    message,
                )

    log.info("done: %d OK, %d FAIL", counters["ok"], counters["fail"])
    log.info("staged under %s", RAW_DIR)
    log.info("NEXT: edit each sidecar .license.json to set license_tag (unverified→spdx),")
    log.info("      then run pnpm ingest:qul-extras / pnpm ingest:qul-recitations / etc.")


if __name__ == "__main__":
    main()
