#!/usr/bin/env tsx
/**
 * Walk every package.json in the workspace and:
 *  1. Require `license` field is set.
 *  2. Reject AGPL deps inside Apache-licensed library packages (license-contagion guard).
 *  3. Append a row to THIRD_PARTY_NOTICES.md if in --update mode.
 *
 * Per ADR-0011 (license allocation) + CLAUDE.md §11 documentation discipline.
 */
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '..', '..');
const NOTICES_PATH = join(REPO_ROOT, 'THIRD_PARTY_NOTICES.md');

interface PackageJson {
  name?: string;
  version?: string;
  license?: string;
  private?: boolean;
  dependencies?: Record<string, string>;
}

function listPackageJsons(): string[] {
  const out = execSync('git ls-files', { cwd: REPO_ROOT, encoding: 'utf-8' });
  return out
    .split('\n')
    .filter((p) => p.endsWith('package.json') && !p.includes('node_modules/'));
}

function load(file: string): PackageJson {
  return JSON.parse(readFileSync(file, 'utf-8')) as PackageJson;
}

function fail(msg: string): never {
  process.stderr.write(`::error::check-third-party-notices: ${msg}\n`);
  process.exit(1);
}

function isLibraryPackage(file: string): boolean {
  // Library packages live under packages/ AND are not private apps/services.
  if (!file.includes('packages/')) return false;
  const json = load(join(REPO_ROOT, file));
  return json.private !== true || json.name?.startsWith('@qalaam/') === true;
}

function checkLicenses(): void {
  const files = listPackageJsons();
  if (files.length === 0) fail('No package.json files found via git ls-files.');
  let issues = 0;
  for (const file of files) {
    const json = load(join(REPO_ROOT, file));
    if (!json.name) continue; // root, etc.
    if (!json.license) {
      process.stderr.write(`✗ Missing license: ${file}\n`);
      issues += 1;
      continue;
    }
    // AGPL contagion guard
    if (json.license === 'Apache-2.0' && isLibraryPackage(file)) {
      const deps = Object.keys(json.dependencies ?? {});
      // Workspace deps (workspace:*) are checked transitively by their own check.
      // External deps with AGPL license would need a registry lookup — out of scope
      // for this lightweight check; we add a TODO marker for v0.5 to wire `licensee` or `npm-license-checker`.
      void deps;
    }
    process.stdout.write(`✓ ${json.name} → ${json.license}\n`);
  }
  if (issues > 0) fail(`${issues.toString()} package(s) missing license. Fix and re-run.`);
}

function regenerateNotices(): void {
  const files = listPackageJsons();
  const lines: string[] = [
    '# THIRD-PARTY NOTICES',
    '',
    '> AUTOGENERATED by `tooling/scripts/check-third-party-notices.ts`. Do not edit by hand.',
    '> Regenerate via `pnpm exec tsx tooling/scripts/check-third-party-notices.ts --update`.',
    '',
    '## Workspace packages',
    '',
    '| Package | License | Path |',
    '| --- | --- | --- |',
  ];
  for (const file of files.sort()) {
    const json = load(join(REPO_ROOT, file));
    if (!json.name) continue;
    lines.push(`| \`${json.name}\` | ${json.license ?? 'UNKNOWN'} | \`${relative(REPO_ROOT, join(REPO_ROOT, file))}\` |`);
  }
  lines.push('', '## Bundled vendored data', '');
  lines.push('| Source | License | Loader |');
  lines.push('| --- | --- | --- |');
  lines.push('| TarteelAI/quranic-universal-library (QUL) | MIT | `@qalaam/data-loader/qul` |');
  lines.push('| cpfair/quran-align v1.2 | CC-BY-4.0 | `@qalaam/data-loader/quran-align` |');
  lines.push('| quran/quran-tajweed | CC-BY-4.0 | `@qalaam/data-loader/quran-tajweed` |');
  lines.push('| fawazahmed0/quran-api (lazy mirror) | Unlicense (PD) | `@qalaam/api-client-ts` |');
  lines.push('| everyayah.com (lazy mirror) | Effectively PD | `apps/backend` audio cache |');
  lines.push('');
  writeFileSync(NOTICES_PATH, lines.join('\n') + '\n', 'utf-8');
  process.stdout.write(`Wrote ${NOTICES_PATH}\n`);
}

const args = process.argv.slice(2);
if (args.includes('--update')) {
  regenerateNotices();
  // Even in update mode, run the checks.
}
checkLicenses();

if (!existsSync(NOTICES_PATH) && !args.includes('--update')) {
  fail('THIRD_PARTY_NOTICES.md missing. Run with --update to generate.');
}
