/**
 * Tier B (per-user) Quran.Foundation API — PKCE + OIDC scaffold.
 *
 * Per ADR-0012 extension + strategy §15 roadmap. v2.0+ surface; the runtime
 * stays disabled (returns 501-equivalent errors) until a Tier B client_id is
 * provisioned and `QF_TIER_B_CLIENT_ID` is present in the environment.
 *
 * The PKCE flow we implement here matches RFC 7636 (S256 challenge method)
 * + OIDC code flow:
 *   1. Generate `code_verifier` (43-128 char URL-safe random) + `state` nonce.
 *   2. Derive `code_challenge = BASE64URL(SHA-256(code_verifier))`.
 *   3. Build the /authorize redirect URL with `response_type=code`,
 *      `code_challenge_method=S256`, `code_challenge`, `state`.
 *   4. Persist {state → code_verifier} in a short-lived store (Redis in
 *      production; in-memory `Map` in dev).
 *   5. On /callback: exchange `code` for tokens via /token, sending the
 *      original `code_verifier` so the auth server can verify.
 *   6. Use the resulting `access_token` (short-lived) + `refresh_token`
 *      (longer-lived) to call Tier B endpoints.
 *
 * The actual `bookmarks/notes/sessions` calls are still 501 here — they
 * require a Tier B credentials provisioning step we haven't completed
 * with Quran.Foundation. The scaffold is in place so the moment the
 * credentials exist, wiring is one config bump + one route handler.
 */
import { QalaamError } from '@qalaam/core';

const CODE_VERIFIER_BYTES = 32; // → 43 base64url chars; well above the 43 floor

export interface PkceChallenge {
  /** The high-entropy random secret kept server-side (NEVER sent to QF /authorize). */
  readonly codeVerifier: string;
  /** SHA-256(codeVerifier), base64url-encoded — the value sent in the /authorize URL. */
  readonly codeChallenge: string;
  /** CSRF nonce; must match on /callback. */
  readonly state: string;
}

export interface QfTierBConfig {
  readonly authorizeUrl: string; // e.g. https://oauth2.quran.foundation/authorize
  readonly tokenUrl: string; // e.g. https://oauth2.quran.foundation/token
  readonly clientId: string;
  readonly redirectUri: string;
  readonly scope?: string; // defaults to "openid profile bookmarks notes sessions"
}

export interface QfTierBTokens {
  readonly accessToken: string;
  readonly refreshToken: string | null;
  readonly idToken: string | null;
  readonly tokenType: string;
  readonly expiresAt: number; // epoch ms
  readonly scope: string;
}

export interface QfUserApiClient {
  /** Phase 1 of OAuth: build the /authorize URL + return the verifier the
   * caller must persist (keyed by `state`). */
  beginPkce(): { url: string; challenge: PkceChallenge };

  /** Phase 2 of OAuth: exchange auth code for tokens (uses the same verifier
   * generated by `beginPkce`). */
  exchangeCode(args: { code: string; codeVerifier: string }): Promise<QfTierBTokens>;

  /** Refresh tokens. */
  refresh(args: { refreshToken: string }): Promise<QfTierBTokens>;

  // — Tier B resource endpoints (still 501 until QF provisioning) —
  listBookmarks(): Promise<never>;
  saveBookmark(verseKey: string): Promise<never>;
  listNotes(): Promise<never>;
}

/**
 * URL-safe base64 (per RFC 7636 §A.2 + RFC 4648 §5): replace `+` → `-`,
 * `/` → `_`, drop `=` padding.
 */
function base64UrlEncode(bytes: Uint8Array): string {
  let bin = '';
  for (const byte of bytes) bin += String.fromCharCode(byte);
  if (typeof btoa === 'function') {
    return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  }
  return Buffer.from(bytes).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function getCrypto(): Crypto {
  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
  if (globalThis.crypto.subtle) {
    return globalThis.crypto;
  }
  throw new QalaamError(
    'qalaam.adapter.capability-unsupported',
    'PKCE requires Web Crypto (globalThis.crypto.subtle). Node ≥ 18 or modern browser only.',
  );
}

async function sha256(input: string): Promise<Uint8Array> {
  const cryptoApi = getCrypto();
  const buf = new TextEncoder().encode(input);
  const digest = await cryptoApi.subtle.digest('SHA-256', buf);
  return new Uint8Array(digest);
}

function randomUrlSafe(byteLen: number): string {
  const cryptoApi = getCrypto();
  const buf = new Uint8Array(byteLen);
  cryptoApi.getRandomValues(buf);
  return base64UrlEncode(buf);
}

/** Generate a PKCE challenge per RFC 7636. Returns the {verifier, challenge, state}
 * tuple; the caller persists `verifier` keyed by `state`. */
export async function generatePkceChallenge(): Promise<PkceChallenge> {
  const codeVerifier = randomUrlSafe(CODE_VERIFIER_BYTES);
  const challengeBytes = await sha256(codeVerifier);
  const codeChallenge = base64UrlEncode(challengeBytes);
  const state = randomUrlSafe(16);
  return { codeVerifier, codeChallenge, state };
}

export function buildAuthorizeUrl(
  config: QfTierBConfig,
  challenge: PkceChallenge,
): string {
  const url = new URL(config.authorizeUrl);
  url.searchParams.set('response_type', 'code');
  url.searchParams.set('client_id', config.clientId);
  url.searchParams.set('redirect_uri', config.redirectUri);
  url.searchParams.set(
    'scope',
    config.scope ?? 'openid profile bookmarks notes sessions',
  );
  url.searchParams.set('code_challenge', challenge.codeChallenge);
  url.searchParams.set('code_challenge_method', 'S256');
  url.searchParams.set('state', challenge.state);
  return url.toString();
}

interface RawTokenResponse {
  access_token: string;
  refresh_token?: string;
  id_token?: string;
  token_type: string;
  expires_in: number;
  scope?: string;
}

async function exchangeAtTokenEndpoint(
  config: QfTierBConfig,
  body: Record<string, string>,
): Promise<QfTierBTokens> {
  const res = await fetch(config.tokenUrl, {
    method: 'POST',
    headers: { 'content-type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams(body).toString(),
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new QalaamError(
      'qalaam.adapter.capability-unsupported',
      `QF Tier B token exchange failed (HTTP ${res.status.toString()}): ${txt}`,
    );
  }
  const json = (await res.json()) as RawTokenResponse;
  return {
    accessToken: json.access_token,
    refreshToken: json.refresh_token ?? null,
    idToken: json.id_token ?? null,
    tokenType: json.token_type,
    expiresAt: Date.now() + json.expires_in * 1000,
    scope: json.scope ?? config.scope ?? 'openid profile bookmarks notes sessions',
  };
}

export interface CreateQfUserApiClientArgs {
  /** When undefined the client returns the legacy "deferred" stub for every
   * call. When provided, PKCE + token exchange go live; resource endpoints
   * still 501 until QF provisioning is signed off. */
  readonly config?: QfTierBConfig;
}

export function createQfUserApiClient(args: CreateQfUserApiClientArgs = {}): QfUserApiClient {
  const config = args.config;

  function notProvisioned(): never {
    throw new QalaamError(
      'qalaam.data.not-loaded',
      'QF Tier B (per-user) endpoints are scaffolded but not yet provisioned. ' +
        'See ADR-0012 + Docs/STRATEGY_AND_ROADMAP.md §15. ' +
        'PKCE/code-exchange stubs are wired; resource endpoints land when QF ' +
        'Tier B credentials are signed off.',
    );
  }

  return {
    beginPkce(): { url: string; challenge: PkceChallenge } {
      if (!config) notProvisioned();
      throw new QalaamError(
        'qalaam.adapter.capability-unsupported',
        'beginPkce is async — call asynchronously: `await beginPkceAsync(config)`.',
      );
    },
    async exchangeCode({ code, codeVerifier }) {
      if (!config) notProvisioned();
      return exchangeAtTokenEndpoint(config, {
        grant_type: 'authorization_code',
        client_id: config.clientId,
        code,
        code_verifier: codeVerifier,
        redirect_uri: config.redirectUri,
      });
    },
    async refresh({ refreshToken }) {
      if (!config) notProvisioned();
      return exchangeAtTokenEndpoint(config, {
        grant_type: 'refresh_token',
        client_id: config.clientId,
        refresh_token: refreshToken,
      });
    },
    listBookmarks: () =>
      Promise.reject(
        new QalaamError(
          'qalaam.data.not-loaded',
          'QF Tier B listBookmarks not yet provisioned. See ADR-0012.',
        ),
      ),
    saveBookmark: () =>
      Promise.reject(
        new QalaamError(
          'qalaam.data.not-loaded',
          'QF Tier B saveBookmark not yet provisioned. See ADR-0012.',
        ),
      ),
    listNotes: () =>
      Promise.reject(
        new QalaamError(
          'qalaam.data.not-loaded',
          'QF Tier B listNotes not yet provisioned. See ADR-0012.',
        ),
      ),
  };
}

/**
 * Async sibling for `beginPkce`: generates the challenge + builds the URL.
 * Exported separately because the client interface is sync-only for legacy
 * symmetry; new callers should prefer this.
 */
export async function beginPkceAsync(
  config: QfTierBConfig,
): Promise<{ url: string; challenge: PkceChallenge }> {
  const challenge = await generatePkceChallenge();
  return { url: buildAuthorizeUrl(config, challenge), challenge };
}
