"""Qalaam Pydantic models — AUTOGENERATED. DO NOT EDIT.

Source of truth: packages/schema/schemas/.
Regenerate via `pnpm codegen` from the repo root.

Models are generated on first `pnpm codegen` invocation.
"""
