#!/usr/bin/env tsx
/**
 * Qalaam codegen runner — one entry point for all generated artifacts.
 *
 * Per ADR-0008: JSON Schema is the single source of truth. This runner produces:
 *   1. TypeScript types  → packages/types-ts/dist/
 *   2. Pydantic v2 models → packages/types-py/qalaam_types/  (delegated to uv-run script)
 *
 * Privacy boundary check (ADR-0005): no audio-bearing types may appear in cloud-sync
 *   transport schemas. Enforced by `check-privacy-boundaries.ts`.
 */
import { execSync } from 'node:child_process';
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '..', '..');
const SCHEMAS_DIR = join(REPO_ROOT, 'packages', 'schema', 'schemas');
const TS_OUT_DIR = join(REPO_ROOT, 'packages', 'types-ts', 'dist');

interface SchemaFile {
  absPath: string;
  relPath: string;
  domain: string;
  basename: string;
}

function listSchemas(): SchemaFile[] {
  const out: SchemaFile[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(path);
      } else if (entry.name.endsWith('.schema.json')) {
        const rel = relative(SCHEMAS_DIR, path);
        const [domain, basename] = rel.split('/') as [string, string];
        out.push({
          absPath: path,
          relPath: rel,
          domain,
          basename: basename.replace('.schema.json', ''),
        });
      }
    }
  };
  walk(SCHEMAS_DIR);
  return out.sort((a, b) => a.relPath.localeCompare(b.relPath));
}

async function generateTypeScript(schemas: SchemaFile[]): Promise<void> {
  console.warn(`→ TS codegen: ${schemas.length.toString()} schemas → ${relative(REPO_ROOT, TS_OUT_DIR)}`);
  // Lazy import to avoid forcing the dep on consumers who don't run codegen.
  const { compileFromFile } = await import('json-schema-to-typescript');

  mkdirSync(TS_OUT_DIR, { recursive: true });

  const indexLines: string[] = [
    '/* AUTOGENERATED by tooling/codegen/run.ts. DO NOT EDIT. */',
    '/* Source of truth: packages/schema/schemas/. */',
    '',
  ];

  for (const s of schemas) {
    const ts = await compileFromFile(s.absPath, {
      bannerComment: '/* AUTOGENERATED. DO NOT EDIT. Source: packages/schema/' + s.relPath + ' */',
      additionalProperties: false,
      strictIndexSignatures: true,
      enableConstEnums: false,
      style: { singleQuote: true, semi: true, trailingComma: 'all', printWidth: 100 },
    });
    const outDir = join(TS_OUT_DIR, s.domain);
    mkdirSync(outDir, { recursive: true });
    const outFile = join(outDir, `${s.basename}.ts`);
    writeFileSync(outFile, ts, 'utf-8');
    indexLines.push(`export * from './${s.domain}/${s.basename}.js';`);
  }
  writeFileSync(join(TS_OUT_DIR, 'index.ts'), indexLines.join('\n') + '\n', 'utf-8');
}

function generatePython(): void {
  console.warn('→ Python codegen: invoking datamodel-code-generator via uv');
  // Delegate to a Python-side script that knows about the workspace layout.
  execSync('uv run python tooling/codegen/run_python.py', {
    cwd: REPO_ROOT,
    stdio: 'inherit',
  });
}

function checkPrivacyBoundaries(schemas: SchemaFile[]): void {
  console.warn('→ Privacy boundary check (ADR-0005)');
  const violations: string[] = [];
  for (const s of schemas) {
    const raw = JSON.parse(readFileSync(s.absPath, 'utf-8')) as { $comment?: string };
    const isLocalOnly = raw.$comment?.includes('LOCAL-ONLY') ?? false;
    const isApiSchema = s.domain === 'api';
    if (isLocalOnly && isApiSchema) {
      violations.push(`${s.relPath}: LOCAL-ONLY schema must not live under schemas/api/`);
    }
  }
  if (violations.length > 0) {
    console.error('✗ Privacy boundary violations:');
    for (const v of violations) console.error('  ' + v);
    process.exit(1);
  }
  console.warn('  ✓ No violations');
}

async function main(): Promise<void> {
  const schemas = listSchemas();
  if (schemas.length === 0) {
    console.error('No schemas found under', SCHEMAS_DIR);
    process.exit(1);
  }
  checkPrivacyBoundaries(schemas);
  await generateTypeScript(schemas);
  generatePython();
  console.warn('✓ Codegen complete');
}

await main();
