#!/usr/bin/env python3
"""Qalaam Python codegen — generate Pydantic v2 models from JSON Schema.

Per ADR-0008: JSON Schema is the single source of truth.
Invoked from `tooling/codegen/run.ts`; do not run directly except for debugging.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMAS_DIR = REPO_ROOT / "packages" / "schema" / "schemas"
PY_OUT_DIR = REPO_ROOT / "packages" / "types-py" / "qalaam_types"


def main() -> None:
    if not SCHEMAS_DIR.exists():
        print(f"Schemas dir not found: {SCHEMAS_DIR}", file=sys.stderr)
        sys.exit(1)

    # Wipe output cleanly to keep generated dir deterministic.
    if PY_OUT_DIR.exists():
        shutil.rmtree(PY_OUT_DIR)
    PY_OUT_DIR.mkdir(parents=True, exist_ok=True)

    # datamodel-code-generator can take a directory and produce one model per file.
    cmd = [
        "datamodel-codegen",
        "--input",
        str(SCHEMAS_DIR),
        "--input-file-type",
        "jsonschema",
        "--output",
        str(PY_OUT_DIR),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.11",
        "--use-standard-collections",
        "--use-union-operator",
        "--snake-case-field",
        "--reuse-model",
        "--field-constraints",
        "--strict-nullable",
        "--use-double-quotes",
        "--use-schema-description",
        "--collapse-root-models",
        "--disable-timestamp",
    ]
    print(f"→ {' '.join(cmd)}")
    result = subprocess.run(cmd, check=False)
    if result.returncode != 0:
        sys.exit(result.returncode)

    # Add module __init__.py for ergonomic import.
    init_path = PY_OUT_DIR / "__init__.py"
    init_path.write_text(
        '"""Qalaam Pydantic models — AUTOGENERATED. DO NOT EDIT.\n\n'
        "Source of truth: packages/schema/schemas/.\n"
        "Regenerate via `pnpm codegen` from the repo root.\n"
        '"""\n',
        encoding="utf-8",
    )
    print(f"✓ Python codegen complete: {PY_OUT_DIR}")


if __name__ == "__main__":
    main()
