/**
 * Adhkar after the obligatory prayer — Hisn al-Muslim §22.
 */
import type { Zikr } from '../types.js';

export const POST_SALAH: readonly Zikr[] = [
  {
    id: 'ps-astaghfirullah-3',
    categories: ['post-salah'],
    title: { en: 'Astaghfirullah ×3' },
    arabic: 'أَسْتَغْفِرُ اللَّهَ',
    transliteration: 'Astaghfirullah',
    translationEn: 'I seek Allah\'s forgiveness.',
    count: 3,
    source: 'Sahih Muslim 591',
    grading: 'sahih',
  },
  {
    id: 'ps-allahumma-anta-as-salam',
    categories: ['post-salah'],
    title: { en: 'O Allah, You are As-Salam' },
    arabic: 'اللَّهُمَّ أَنْتَ السَّلَامُ، وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ',
    translationEn:
      'O Allah, You are Peace, and from You comes peace. Blessed are You, Possessor of Majesty and Honor.',
    count: 1,
    source: 'Sahih Muslim 591',
    grading: 'sahih',
  },
  {
    id: 'ps-tasbih-33',
    categories: ['post-salah', 'general'],
    title: { en: 'SubhanAllah ×33' },
    arabic: 'سُبْحَانَ اللَّهِ',
    transliteration: 'SubhanAllah',
    translationEn: 'Glory be to Allah.',
    count: 33,
    source: 'Sahih Muslim 596',
    grading: 'sahih',
  },
  {
    id: 'ps-tahmid-33',
    categories: ['post-salah', 'general'],
    title: { en: 'Alhamdulillah ×33' },
    arabic: 'الْحَمْدُ لِلَّهِ',
    transliteration: 'Alhamdulillah',
    translationEn: 'All praise is for Allah.',
    count: 33,
    source: 'Sahih Muslim 596',
    grading: 'sahih',
  },
  {
    id: 'ps-takbir-33',
    categories: ['post-salah', 'general'],
    title: { en: 'Allahu Akbar ×33' },
    arabic: 'اللَّهُ أَكْبَرُ',
    transliteration: 'Allahu Akbar',
    translationEn: 'Allah is the Greatest.',
    count: 33,
    source: 'Sahih Muslim 596',
    grading: 'sahih',
    gradingNotes: 'Plus the closing tahleel below to complete to 100.',
  },
  {
    id: 'ps-tahleel-100-completion',
    categories: ['post-salah'],
    title: { en: 'Closing tahleel after 33-33-33 (sins forgiven even if like foam of the sea)' },
    arabic:
      'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    translationEn:
      'There is no god but Allah alone, with no partner; His is the dominion, His is the praise, and He is over all things competent.',
    count: 1,
    source: 'Sahih Muslim 597',
    grading: 'sahih',
  },
  {
    id: 'ps-la-hawla-wa-la-quwwata',
    categories: ['post-salah', 'general'],
    title: { en: 'There is no power and no might except by Allah' },
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'La hawla wa la quwwata illa billah',
    translationEn: 'There is no power and no might except by Allah.',
    count: 1,
    source: 'Sahih Bukhari 7386',
    grading: 'sahih',
    gradingNotes: 'A treasure from the treasures of Paradise.',
  },
  {
    id: 'ps-allahumma-aini-ala-dhikrika',
    categories: ['post-salah'],
    title: { en: 'O Allah, help me to remember You' },
    arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ، وَشُكْرِكَ، وَحُسْنِ عِبَادَتِكَ',
    translationEn: 'O Allah, help me to remember You, to thank You, and to worship You in the best manner.',
    count: 1,
    source: 'Sunan Abi Dawud 1522, al-Nasa\'i 1303',
    grading: 'sahih',
    gradingNotes: 'The Prophet ﷺ told Mu\'adh to never miss this after every prayer.',
  },
  {
    id: 'ps-ayat-al-kursi-after-salah',
    categories: ['post-salah'],
    title: { en: 'Ayat al-Kursi after every prayer' },
    arabic:
      'ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۚ ...',
    translationEn:
      'Ayat al-Kursi (2:255) — recited in full. Whoever recites it after every obligatory prayer, nothing prevents them from entering Paradise except death.',
    count: 1,
    source: 'al-Nasa\'i in al-Kubra 9928',
    grading: 'sahih',
    gradingNotes: 'Sahih per Albani in Sahih al-Jami\' 6464.',
    verseKey: '2:255',
  },
  {
    id: 'ps-3-quls-after-salah',
    categories: ['post-salah'],
    title: { en: 'The 3 Quls after every prayer' },
    arabic: '﴿قُلْ هُوَ اللَّهُ أَحَدٌ﴾ + ﴿قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ﴾ + ﴿قُلْ أَعُوذُ بِرَبِّ النَّاسِ﴾',
    translationEn: 'Surahs Al-Ikhlas, Al-Falaq, Al-Nas — recited after every obligatory prayer.',
    count: 1,
    source: 'Sunan Abi Dawud 1523, Tirmidhi 2903',
    grading: 'sahih',
    gradingNotes: '3× after Fajr and Maghrib per other narrations.',
    verseKey: '112:1',
  },
];
